import { icons } from '@/components/icons';
import type { AiDevelopment } from './types';

export const aiDevelopmentsData: AiDevelopment[] = [
    { category: 'tools', title: 'إطلاق عائلة نماذج Gemini 2.5', date: 'يونيو 2025', source: 'مدونة Google الرسمية', icon: icons.tools, shortDesc: 'النموذج الأكثر تقدمًا مع قدرات استدلال وترميز محسّنة.', details: ['**Gemini 2.5 Pro:** أصبح متاحًا بشكل عام، وهو النموذج الأساسي المتقدم.', '**Deep Think:** وضع تجريبي جديد في 2.5 Pro لحل المشكلات المعقدة للغاية.', '**Gemini 2.5 Flash & Flash-Lite:** إصدارات أسرع وأكثر كفاءة للمهام التي تتطلب استجابة سريعة.', '**قدرات صوتية متقدمة:** حوار وتوليد صوتي متقدم لتفاعل أكثر طبيعية.'], link: 'https://blog.google/technology/developers/google-io-2025-collection/' },
    { category: 'products', title: 'ثورة في بحث Google مع "وضع الذكاء الاصطناعي"', date: 'مايو 2025', source: 'مدونة بحث جوجل', icon: icons.products, shortDesc: 'تحويل البحث إلى تجربة حوارية تفاعلية مع قدرات بحث عميقة.', details: ['**تعميم AI Mode:** تم إطلاقه في الولايات المتحدة، يتيح طرح أسئلة معقدة ومتابعة الحوار.', '**البحث العميق (Deep Search):** ميزة لاستكشاف الموضوعات المعقدة.', '**قدرات تفاعلية حية (Live Capabilities):** سيتمكن المستخدمون قريبًا من التحدث مع البحث حول ما يرونه عبر الكاميرا.', '**وكلاء مهام (Agents):** سيساعدك البحث في مهام مثل التخطيط للرحلات أو التسوق.'], link: 'https://blog.google/products/search/google-search-ai-mode-update/' },
    { category: 'tools', title: 'أدوات إعلام إبداعية: Veo 3, Imagen 4, Flow', date: 'مايو 2025', source: 'مدونة Google الرسمية', icon: icons.tools, shortDesc: 'مجموعة أدوات ثورية لتوليد الفيديو والصور وصناعة الأفلام.', details: ['**Veo 3:** أحدث طراز لتوليد الفيديو من النص بجودة 1080p وفهم سينمائي.', '**Imagen 4:** النموذج الأكثر قدرة لتحويل النص إلى صور، متاح الآن في تطبيق Gemini.', '**Flow:** أداة جديدة لصناعة الأفلام بالذكاء الاصطناعي، تدمج Veo و Imagen.'], link: 'https://blog.google/technology/ai/google-io-2025-all-our-announcements/' },
    { category: 'official', title: 'Project Astra: مستقبل المساعدين الأذكياء', date: 'مايو 2025', source: 'Google I/O 2025', icon: icons.official, shortDesc: 'استعراض لمساعد ذكاء اصطناعي عالمي يمكنه الرؤية والتذكر والفهم.', details: ['**رؤية طويلة الأمد:** يمثل Project Astra رؤية Google لمستقبل المساعدين الأذكياء.', '**متعدد الوسائط وفي الوقت الفعلي:** يفهم المدخلات من الكاميرا والصوت بشكل متزامن.', '**ذاكرة سياقية:** يتذكر ما رآه سابقًا للإجابة على الأسئلة المتعلقة به لاحقًا.', '**لا يزال قيد التطوير:** سيتم دمج تقنياته تدريجيًا في منتجات Google.'], link: '#' },
    { category: 'community', title: 'Google Colab يعتمد على الذكاء الاصطناعي أولاً', date: 'يونيو 2025', source: 'مدونة مطوري جوجل', icon: icons.community, shortDesc: 'تحويل Colab إلى مساعد برمجة حقيقي لتسريع مشاريع تعلم الآلة.', details: ['**مساعد برمجة متكامل:** يساعد في دورة حياة تعلم الآلة بالكامل.', '**تصحيح أخطاء ذكي:** لا يكتشف الأخطاء فحسب، بل يقترح إصلاحات لها.', '**تجربة حوارية:** يحول ساعات من العمل اليدوي إلى حوار موجه.', '**موجه للمطورين:** يستهدف بشكل أساسي مجتمع المطورين وعلماء البيانات.'], link: 'https://developers.googleblog.com/en/new-ai-first-google-colab-now-available-to-everyone/' },
    { category: 'products', title: 'دمج AI في Google Workspace', date: 'مستمر 2025', source: 'Google Workspace Updates', icon: icons.products, shortDesc: 'ميزات ذكاء اصطناعي متقدمة في Gmail, Docs, Sheets لمساعدتك في الكتابة والتنظيم.', details: ['**Help me write:** إنشاء مسودات وتلخيص رسائل البريد الإلكتروني والمستندات.', '**Help me organize:** إنشاء جداول وقوالب مخصصة تلقائيًا من وصف نصي.', '**Help me visualize:** إنشاء صور فريدة للعروض التقديمية من خلال وصف بسيط.', '**Vids:** تطبيق جديد لإنشاء الفيديو لمساعدتك في سرد قصص العمل.'], link: '#' },
    { category: 'official', title: 'مشروع Google Beam (Starline سابقًا)', date: 'متوقع في 2025', source: 'Google I/O 2025', icon: icons.official, shortDesc: 'مشروع مكالمات الفيديو ثلاثية الأبعاد سيتم إطلاقه قريبًا عبر أجهزة HP.', details: ['**تقنية العرض الضوئي:** يخلق صورة ثلاثية الأبعاد واقعية للشخص الذي تتحدث معه.', '**شراكة مع HP:** سيتم إطلاق التقنية تجاريًا من خلال أجهزة تحمل علامة HP.', '**تجربة تواصل غامرة:** يهدف لجعل التفاعلات عن بعد تبدو وكأنها وجهًا لوجه.'], link: '#' },
    { category: 'official', title: 'DeepMind تطلق AlphaGenome', date: 'يونيو 2025', source: 'مدونة DeepMind', icon: icons.official, shortDesc: 'نموذج جديد لفهم تسلسل الحمض النووي (DNA) والتنبؤ بتأثيرات المتغيرات الجينية.', details: ['**فهم الجينوم:** يهدف إلى تسريع الأبحاث في علم الجينوم وفهم الأمراض الوراثية.', '**تنبؤ دقيق:** يتنبأ بكيفية تأثير الطفرات الجينية على وظائف الخلايا.', '**متاح للباحثين:** تم توفير النموذج عبر واجهة برمجية (API) لمجتمع البحث العلمي.'], link: 'https://deepmind.google/discover/blog/alphagenome-ai-for-better-understanding-the-genome/' }
];

export const getCategoryText = (category: AiDevelopment['category']) => {
    switch (category) {
        case 'official': return 'رسمي';
        case 'tools': return 'أدوات ونماذج';
        case 'products': return 'منتجات';
        case 'community': return 'مجتمعي';
        default: return 'عام';
    }
};
